baseurl = "/"
languageCode = "en-us"
title = "Xiaoqi Tan"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"


[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Research"
    url = "/research"
    weight = 2

[[menu.main]]
    name = "Publications"
    url = "/publications_year"
    weight = 4

[[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 5

[[menu.main]]
    name = "Join"
    url = "/join"
    weight = 6

[params]
    description = "A website built through Hugo and blogdown."
    footer = "Copyright &copy; 2021  [Xiaoqi Tan](https://xiaoqitan.org)"

[blackfriday]
hrefTargetBlank = true